// Code generated by goctl. DO NOT EDIT!
// Source: transform.proto

package server

import (
	"context"

	"github.com/dfang/shorturl/rpc/internal/logic"
	"github.com/dfang/shorturl/rpc/internal/svc"
	"github.com/dfang/shorturl/rpc/transform"
)

type TransformServiceServer struct {
	svcCtx *svc.ServiceContext
	transform.UnimplementedTransformServiceServer
}

func NewTransformServiceServer(svcCtx *svc.ServiceContext) *TransformServiceServer {
	return &TransformServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TransformServiceServer) Expand(ctx context.Context, in *transform.ExpandRequest) (*transform.ExpandResponse, error) {
	l := logic.NewExpandLogic(ctx, s.svcCtx)
	return l.Expand(in)
}

func (s *TransformServiceServer) Shorten(ctx context.Context, in *transform.ShortenRequest) (*transform.ShortenResponse, error) {
	l := logic.NewShortenLogic(ctx, s.svcCtx)
	return l.Shorten(in)
}
