// Code generated by goctl. DO NOT EDIT!
// Source: transform.proto

package transformservice

import (
	"context"

	"github.com/dfang/shorturl/rpc/transform"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExpandRequest   = transform.ExpandRequest
	ExpandResponse  = transform.ExpandResponse
	ShortenRequest  = transform.ShortenRequest
	ShortenResponse = transform.ShortenResponse

	TransformService interface {
		Expand(ctx context.Context, in *ExpandRequest, opts ...grpc.CallOption) (*ExpandResponse, error)
		Shorten(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenResponse, error)
	}

	defaultTransformService struct {
		cli zrpc.Client
	}
)

func NewTransformService(cli zrpc.Client) TransformService {
	return &defaultTransformService{
		cli: cli,
	}
}

func (m *defaultTransformService) Expand(ctx context.Context, in *ExpandRequest, opts ...grpc.CallOption) (*ExpandResponse, error) {
	client := transform.NewTransformServiceClient(m.cli.Conn())
	return client.Expand(ctx, in, opts...)
}

func (m *defaultTransformService) Shorten(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenResponse, error) {
	client := transform.NewTransformServiceClient(m.cli.Conn())
	return client.Shorten(ctx, in, opts...)
}
